version: "3"

services:
  user_management_db:
    image: postgres
    container_name: user_management_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: user_management_db
    restart: always
    volumes:
      - ./user_management/db_data/:/var/lib/postgresql/data

