version: "3"

services:
  postgres:
    image: postgres
    container_name: user_management_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: user_management_db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./user_management/db_data/:/var/lib/postgresql/data

  yourgoapp:
    image: user_management
    container_name: user_management
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: user_management_db
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
